package entity;
// Generated Nov 16, 2017 1:24:44 PM by Hibernate Tools 4.3.1



/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int idGrupo;
     private String nombre;
     private int idProfesor;

    public Grupo() {
    }

	
    public Grupo(int idGrupo, int idProfesor) {
        this.idGrupo = idGrupo;
        this.idProfesor = idProfesor;
    }
    public Grupo(int idGrupo, String nombre, int idProfesor) {
       this.idGrupo = idGrupo;
       this.nombre = nombre;
       this.idProfesor = idProfesor;
    }
   
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }




}


