package entity;
// Generated Nov 16, 2017 1:24:44 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuario;
     private String usuario;
     private String contrasena;
     private Integer tipoUsuario;

    public Usuarios() {
    }

	
    public Usuarios(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuarios(int idUsuario, String usuario, String contrasena, Integer tipoUsuario) {
       this.idUsuario = idUsuario;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.tipoUsuario = tipoUsuario;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Integer getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(Integer tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }




}


