package entity;
// Generated Nov 18, 2017 3:49:41 PM by Hibernate Tools 4.3.1



/**
 * Calificaciones generated by hbm2java
 */
public class Calificaciones  implements java.io.Serializable {


     private Integer idCalificacion;
     private Usuarios usuarios;
     private Integer calificacion;

    public Calificaciones() {
    }

	
    public Calificaciones(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Calificaciones(Usuarios usuarios, Integer calificacion) {
       this.usuarios = usuarios;
       this.calificacion = calificacion;
    }
   
    public Integer getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(Integer idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }




}


