package entity;
// Generated 10/12/2017 11:50:48 PM by Hibernate Tools 4.3.1



/**
 * Resultados generated by hbm2java
 */
public class Resultados  implements java.io.Serializable {


     private Integer idResultado;
     private Tareas tareas;
     private Usuarios usuarios;
     private String resultado1;
     private String resultado2;
     private String resultado3;
     private String resultado4;

    public Resultados() {
    }

	
    public Resultados(Tareas tareas, Usuarios usuarios) {
        this.tareas = tareas;
        this.usuarios = usuarios;
    }
    public Resultados(Tareas tareas, Usuarios usuarios, String resultado1, String resultado2, String resultado3, String resultado4) {
       this.tareas = tareas;
       this.usuarios = usuarios;
       this.resultado1 = resultado1;
       this.resultado2 = resultado2;
       this.resultado3 = resultado3;
       this.resultado4 = resultado4;
    }
   
    public Integer getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(Integer idResultado) {
        this.idResultado = idResultado;
    }
    public Tareas getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Tareas tareas) {
        this.tareas = tareas;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getResultado1() {
        return this.resultado1;
    }
    
    public void setResultado1(String resultado1) {
        this.resultado1 = resultado1;
    }
    public String getResultado2() {
        return this.resultado2;
    }
    
    public void setResultado2(String resultado2) {
        this.resultado2 = resultado2;
    }
    public String getResultado3() {
        return this.resultado3;
    }
    
    public void setResultado3(String resultado3) {
        this.resultado3 = resultado3;
    }
    public String getResultado4() {
        return this.resultado4;
    }
    
    public void setResultado4(String resultado4) {
        this.resultado4 = resultado4;
    }




}


